exp_name: block_diagonal_ngf_10k_v2_cross
node_layers:
  - layers.0
  - layers.1
  - layers.2
  - layers.3
  - layers.4
  - layers.5
  - layers.6
  - layers.7
  - layers.8
  - layers.9
  - layers.10
  - layers.11
  - layers.12
  - layers.13
  - layers.14
  - layers.15
  - output
dataset:
  dataset_type: block_vector
  size: 10000
  length: 20
  data_variances: [1, 1]
  data_perfect_correlation: false
  seed: 0
modular_mlp_config:
  n_hidden_layers: 15
  width: 20
  mixing_layers: [14]
  weight_variances: [1., 1., 0.3, 0.3]
  weight_equal_columns: false
  bias: 0
seed: 0
dtype: float64
batch_size: 100000
gram_batch_size: 100000
edge_batch_size: 100000
n_intervals: 0
truncation_threshold: 1e-15
rotate_final_node_layer: false
basis_formula: jacobian
edge_formula: squared
center: true
naive_gradient_flow: true