exp_name: modular_arithmetic
seed: 0
tlens_pretrained: null
tlens_model_path: rib_scripts/train_modular_arithmetic/sample_checkpoints/lr-0.001_bs-10000_norm-None_2023-11-28_16-07-19/model_epoch_60000.pt
interaction_matrices_path: null
dataset:
  dataset_type: modular_arithmetic
  return_set: train
node_layers:
  - ln1.0
  - ln2.0
  - mlp_out.0
  - unembed
  - output
rotate_final_node_layer: false
last_pos_module_type: add_resid1 # module type in which to only output the last position index
eval_type: accuracy
gram_batch_size: 20000 # full dataset
batch_size: 20000 # full dataset
edge_batch_size: 20000 # full dataset
calculate_edges: true
truncation_threshold: 1e-15
dtype: float64
n_intervals: 0
basis_formula: jacobian
edge_formula: squared
n_stochastic_sources_basis_pos: null
n_stochastic_sources_basis_hidden: null
n_stochastic_sources_edges: null
