# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: ["--check", "--line-length", "100", "rib", "scripts", "tests"]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--check", "--thirdparty", "wandb", "--profile", "black", "rib", "scripts", "tests"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.4.1'
    hooks:
    -   id: mypy
        name: mypy-rib
        files: ^rib/
        entry: mypy rib/
        pass_filenames: false
        additional_dependencies: [types-PyYAML, types-tqdm]
    -   id: mypy
        name: mypy-scripts
        files: ^scripts/
        entry: mypy scripts/
        pass_filenames: false
        additional_dependencies: [types-PyYAML, types-tqdm, wandb]  # Needed to avoid attribute errors
