#!/bin/sh

check_command() {
    # Run command and check if it fails. If it fails, print output and continue.
    # If it succeeds, suppress output and continue.
    output=$("$@" 2>&1)
    status=$?
    if [ $status -ne 0 ]; then
        echo "$output"
    fi

    return $status
}

check_command black --check --line-length 100 rib scripts tests
check_command isort --check --profile black rib scripts tests
check_command mypy --strict rib scripts
check_command pytest tests
