pytest --runmpi tests/test_distributed.py::test_squared_edges_are_same_dist_split_over_dataset
pytest --runmpi tests/test_distributed.py::test_squared_edges_are_same_dist_split_over_out_dim
pytest --runmpi tests/test_distributed.py::test_stochastic_edges_are_same_dist_split_over_out_dim
pytest --runmpi tests/test_distributed.py::test_distributed_basis