mlp_name: 1-layer
mlp_path: "/mnt/ssd-apollo/checkpoints/MNIST/lr-0.001_bs-64_2023-07-03_15-26-43/model_epoch_12.pt"
hook_configs:
  - hook_name: inputs
    module_name: layers.linear_0
    hook_type: pre_forward
    layer_size: 784
  - hook_name: act_layer_0
    module_name: layers.act_0
    hook_type: forward
    layer_size: 100