data:
  name: CIFAR10
  return_set_frac: null
  return_set_n_samples: null
  seed: 0
model:
  activation_fn: relu
  bias: true
  dtype: float32
  fold_bias: false
  hidden_sizes:
  - 50
  - 50
  input_size: 3072
  output_size: 10
seed: 0
train:
  batch_size: 64
  epochs: 12
  learning_rate: 0.001
  save_dir: /mnt/ssd-apollo/nix/interp/interp/mlp_analysis/out/models
  save_every_n_epochs: null
wandb: null
