seed: 0
model:
  hidden_sizes:
    - 100
  activation_fn: relu
train:
  learning_rate: 0.001
  batch_size: 64
  epochs: 15
  save_dir: /mnt/ssd-apollo/checkpoints/MNIST
  save_every_n_epochs: null
wandb:
  project: mlp-mnist
  entity: dbra
