exp_name: rib_modular_arithmetic-stochastic_0
ablation_type: edge
rib_results_path: /mnt/ssd-interp/stefan/rib/rib_scripts/rib_build/out/modular_arithmetic-stochastic_0_rib_graph.pt
schedule:
  schedule_type: exponential
  early_stopping_threshold: null
  ablate_every_vec_cutoff: 0
  exp_base: 1.1
dataset:
  dataset_type: modular_arithmetic
  return_set: train
ablation_node_layers:  # Rotate the input to these modules into the interaction basis
  - ln1.0
  - ln2.0
batch_size: 128
dtype: float32
eval_type: accuracy
seed: 0
