exp_name: rib_modular_arithmetic #_naive_gradient_flow
ablation_type: rib
rib_results_path: /home/user/rib/rib_scripts/rib_build/out/modular_arithmetic_rib_graph.pt #_naive_gradient_flow
schedule:
  schedule_type: exponential
  early_stopping_threshold: null
  ablate_every_vec_cutoff: 10
  exp_base: 2
dataset:
  dataset_type: modular_arithmetic
  return_set: train
ablation_node_layers:  # Rotate the input to these modules into the interaction basis
  - ln1.0
  - ln2.0
  - mlp_out.0
  - unembed
batch_size: 128
dtype: float32
eval_type: accuracy
seed: 0
