exp_name: rib_pythia-14m-NGF
ablation_type: rib
rib_results_path: rib_scripts/rib_build/out/pythia-14m-NGF_rib_Cs.pt
schedule:
  schedule_type: linear
  early_stopping_threshold: 1.5
  n_points: 20
  specific_points: [128, 129, 130]
dataset:
  dataset_type: huggingface
  name: NeelNanda/pile-10k
  tokenizer_name: EleutherAI/pythia-14m
  return_set: train  # pile-10k only has train, so we take the first 90% for building and last 10% for ablations
  n_samples: 10
  # n_documents: 10
  return_set_portion: first
ablation_node_layers:
  - ln1.0
  - mlp_out.0
  - ln2.3
  - mlp_out.3
  - ln1.5
batch_size: 30  # A100 can handle 60
dtype: float32
eval_type: ce_loss
seed: 0
