exp_name: tinystories_unweighted_gram
ablation_type: rib
rib_results_path: rib_scripts/rib_build/out/tinystories_unweighted_gram_rib_Cs.pt
schedule:
  schedule_type: linear
  # early_stopping_threshold: 1.5
  n_points: 20
  specific_points: [128, 129, 130]
dataset:
  dataset_type: huggingface
  name: roneneldan/TinyStories
  tokenizer_name: EleutherAI/gpt-neo-125M
  return_set: validation
  return_set_frac: null
  n_documents: 1000  # avg ~235 toks / story
  n_samples: 100
  return_set_portion: first
  n_ctx: 256 # needs to be <= 511 for the model to behave reasonably
ablation_node_layers:
  - ln1.4
  - mlp_out.4
  - ln1.7
  - mlp_out.7
batch_size: 10  # A100 can handle 60
dtype: float64
eval_type: ce_loss
seed: 0
