exp_name: gpt2
out_dir: /mnt/ssd-rib/gpt2/
seed: 0
tlens_pretrained: gpt2
tlens_model_path: null
dataset:
  dataset_type: huggingface
  name: apollo-research/Skylion007-openwebtext-tokenizer-gpt2
  tokenizer_name: gpt2
  return_set: train
  return_set_frac: null
  n_documents: 100000
  n_samples: 500
  # 60 samples @ 128 ctx (batch size 20) = 7.3 minutes, max usage 66 GB VRAM (nvidia-smi)
  # 9 samples @ 1024 ctx (batch size 3) = 11 minutes, max usage 68 GB VRAM (nvidia-smi)
  # 500 samples @ 1024 ctx ~ 10h; start 7th March
  return_set_portion: first
  n_ctx: 1024
  seed: 0
gram_dataset:
  dataset_type: huggingface
  name: apollo-research/Skylion007-openwebtext-tokenizer-gpt2
  tokenizer_name: gpt2
  return_set: train
  return_set_frac: null
  n_documents: 100000
  n_samples: 50000
  return_set_portion: first
  n_ctx: 1024
  seed: 0
eval_type: null
# RIB layers
node_layers:
  - ln1.0
  - ln1_out.0
  - attn_in.0
  - ln2.0
  - ln2_out.0
  - mlp_in.0
  - ln1.1
  - ln1_out.1
  - attn_in.1
  - ln2.1
  - ln2_out.1
  - mlp_in.1
  - ln1.2
  - ln1_out.2
  - attn_in.2
  - ln2.2
  - ln2_out.2
  - mlp_in.2
  - ln1.3
  - ln1_out.3
  - attn_in.3
  - ln2.3
  - ln2_out.3
  - mlp_in.3
  - ln1.4
  - ln1_out.4
  - attn_in.4
  - ln2.4
  - ln2_out.4
  - mlp_in.4
  - ln1.5
  - ln1_out.5
  - attn_in.5
  - ln2.5
  - ln2_out.5
  - mlp_in.5
  - ln1.6
  - ln1_out.6
  - attn_in.6
  - ln2.6
  - ln2_out.6
  - mlp_in.6
  - ln1.7
  - ln1_out.7
  - attn_in.7
  - ln2.7
  - ln2_out.7
  - mlp_in.7
  - ln1.8
  - ln1_out.8
  - attn_in.8
  - ln2.8
  - ln2_out.8
  - mlp_in.8
  - ln1.9
  - ln1_out.9
  - attn_in.9
  - ln2.9
  - ln2_out.9
  - mlp_in.9
  - ln1.10
  - ln1_out.10
  - attn_in.10
  - ln2.10
  - ln2_out.10
  - mlp_in.10
  - ln1.11
  - ln1_out.11
  - attn_in.11
  - ln2.11
  - ln2_out.11
  - mlp_in.11
  - ln_final
  - ln_final_out
  - unembed
rotate_final_node_layer: true
# GPUs
gram_batch_size: 4
batch_size: 3 #30 @ 128ctx is too much for single GPU, 20 works
edge_batch_size: 3
dist_split_over: out_dim
# Common
dtype: float64
truncation_threshold: 1e-15
n_intervals: 0
integration_method: gradient
center: true
# Gram matrices
gram_matrices_path: /mnt/ssd-rib/gpt2/gpt2_rib_grams.pt
# Basis matrices
calculate_Cs: true
interaction_matrices_path: null
basis_formula: jacobian
naive_gradient_flow: false
n_stochastic_sources_basis_pos: 1
n_stochastic_sources_basis_hidden: null
# Edges
calculate_edges: false
edge_formula: squared
n_stochastic_sources_edges: 1