name: Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
    - name: Check with Black
      run: |
        black --check --diff --line-length 100 rib scripts
    - name: Check with isort
      run: |
        isort --check --profile black rib scripts
    - name: Check with mypy
      run: |
        mypy --strict rib scripts