name: Checks
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
      - 'ACCESS.md'
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
      - 'ACCESS.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev
        python -m pip install --upgrade pip
        pip install ".[dev]"
    - name: Check with Black
      run: |
        black --check --diff --line-length 100 rib rib_scripts tests
    - name: Check with isort
      run: |
        isort --check --thirdparty wandb --profile black rib rib_scripts tests
    - name: Check unused imports with pylint
      run: |
        pylint --disable=all --enable=unused-import --score=n rib rib_scripts tests
    - name: Check with mypy
      run: |
        mypy rib rib_scripts
    - name: Run tests # Can only run fast tests on cpu runner
      run: |
        pytest --durations=10