name: Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
      - 'ACCESS.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
      - 'ACCESS.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up or use existing virtual environment
      run: |
        VENV_PATH="/home/user/actions-runner/rib-env"
        if [ ! -d "$VENV_PATH" ]; then
          echo "Creating a new virtual environment."
          python -m venv "$VENV_PATH"
        else
          echo "Using existing virtual environment."
        fi

    - name: Install or update dependencies
      run: |
        source /home/user/actions-runner/rib-env/bin/activate
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Check with Black
      run: |
        source /home/user/actions-runner/rib-env/bin/activate
        black --check --diff --line-length 100 rib rib_scripts tests

    - name: Check with isort
      run: |
        source /home/user/actions-runner/rib-env/bin/activate
        isort --check --thirdparty wandb --profile black rib rib_scripts tests

    - name: Check unused imports with pylint
      run: |
        source /home/user/actions-runner/rib-env/bin/activate
        pylint --disable=all --enable=unused-import --score=n rib rib_scripts tests

    - name: Check with mypy
      run: |
        source /home/user/actions-runner/rib-env/bin/activate
        mypy rib rib_scripts

    - name: Run tests
      # Note that we run need to run the distributed tests in separate processes
      run: |
        source /home/user/actions-runner/rib-env/bin/activate
        pytest --runslow --durations=10
        pytest --runmpi tests/test_distributed.py::test_squared_edges_are_same_dist_split_over_dataset
        pytest --runmpi tests/test_distributed.py::test_squared_edges_are_same_dist_split_over_out_dim
        pytest --runmpi tests/test_distributed.py::test_stochastic_edges_are_same_dist_split_over_out_dim
