name: Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
      - 'ACCESS.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
      - 'ACCESS.md'

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Set up or use existing virtual environment
      run: |
        if [ ! -d "venv" ]; then
          echo "Creating a new virtual environment."
          python -m venv venv
        else
          echo "Using existing virtual environment."
        fi

    - name: Install or update dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Check with Black
      run: |
        source venv/bin/activate
        black --check --diff --line-length 100 rib experiments tests

    - name: Check with isort
      run: |
        source venv/bin/activate
        isort --check --thirdparty wandb --profile black rib experiments tests

    - name: Check with mypy
      run: |
        source venv/bin/activate
        mypy rib experiments

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest --runslow -m "not skip_ci" --durations=10