name: Checks

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
      - 'ACCESS.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
      - 'ACCESS.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Determine VENV_PATH
      run: |
        if [ -d "/home/user/actions-runner" ]; then
          VENV_PATH="/home/user/actions-runner/rib-env"
        else
          VENV_PATH="${{ github.workspace }}/rib-env"
        fi
        echo "VENV_PATH=$VENV_PATH" >> $GITHUB_ENV

    - name: Set up or use existing virtual environment
      run: |
        if [ ! -d "$VENV_PATH" ]; then
          echo "Creating a new virtual environment at $VENV_PATH."
          python -m venv "$VENV_PATH"
        else
          echo "Using existing virtual environment at $VENV_PATH."
        fi

    - name: Install or update dependencies
      run: |
        source $VENV_PATH/bin/activate
        python -m pip install --upgrade pip
        pip install ".[dev]"

    - name: Check with Black
      run: |
        source $VENV_PATH/bin/activate
        black --check --diff --line-length 100 rib rib_scripts tests

    - name: Check with isort
      run: |
        source $VENV_PATH/bin/activate
        isort --check --thirdparty wandb --profile black rib rib_scripts tests

    - name: Check unused imports with pylint
      run: |
        source $VENV_PATH/bin/activate
        pylint --disable=all --enable=unused-import --score=n rib rib_scripts tests

    - name: Check with mypy
      run: |
        source $VENV_PATH/bin/activate
        mypy rib rib_scripts

    - name: Run tests
      run: |
        source $VENV_PATH/bin/activate
        pytest --runslow -m "not skip_ci" --durations=10
