name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy
    - name: Check with Black
      run: |
        black --check --line-length 100 rib scripts
    - name: Check with isort
      run: |
        isort --check --profile black rib scripts
    - name: Check with mypy
      run: |
        mypy --strict rib scripts